### ISSUE TITLE
Dev server doesn't do anything

### ISSUE THREAD

**Issue by TheAlphaNerd** [bigboringsystem/bigboringsystem#107]
if you just run ```npm run dev``` there is no server running on port 3000 (this is if you do not have a local.json included).

I will dig more into what is happening when I have some free time

**Comment by jasonrhodes** [comment]
Hmm, maybe a better option for this is just using 
```
nconf.defaults({
  port: 3000,
  cookie: secret
});
```
and this way to get the server running fast for local dev, you don't need to mess with local.json at all?

This works great for me. If we go this route, lets catch the error in the `server.start()` callback and fail gracefully if the server doesn't start, otherwise print out data about what domain and port we're listening on using `server.info().uri`

**Comment by isaacs** [comment]
Closed by #110
