### ISSUE TITLE
Make footer a config thingie?

### ISSUE THREAD

**Issue by isaacs** [bigboringsystem/bigboringsystem#115]
Maybe the "powered by" bit at the bottom should be a config?  Seems like it might not be a thing that everyone would want there, and easier to just configure in local.json than force forks to float a patch.

**Comment by jasonrhodes** [comment]
Makes total sense to me.

**Comment by isaacs** [comment]
Ugh, this is kind of painful to work in, though.  Otherwise it has to be passed to every single `reply.view` call, looks like.  It'd be nice if Hapi had something like templar's default context settings that could be set in one place.

Punting for now.  Changing views/layout.jade isn't any harder than changing local.json.

**Comment by jasonrhodes** [comment]
Looks like you can tap into the reply stream and add stuff, like this:

https://github.com/poeticninja/hapi-cache-buster/blob/master/index.js#L22-L28

**Comment by isaacs** [comment]
Yeah, but then we have to put some markdown in a config... and just... ugh.  Too much work, not enough benefit.

That hapi-cache-buster is pretty relevant to #184 though!

**Comment by gggritso** [comment]
So, since BBS is a private package people are going to be deploying their BBS instances using Docker, or just forking the repo and doing it manually, right?

Also, the footer should probably support arbitrary HTML, since adding Markdown support for _just_ the footer is kind of ham-fisted and having only plaintext isn't good enough. My question then is whether we should just break the footer into its own .jade file and tell people to customize that directly.

We could make it a little easier on the user by letting them put the footer (and potentially a `header.jade` and a `more.jade`) file into another directory on the system and then add it to the jade lookup path (not sure if this is possible). The path, then would be a setting in `local.json`.

What do you think?

**Comment by isaacs** [comment]
Editing `footer.jade` isn't any easier than editing `layout.jade` for this.

The "feature", if we decide to add it, would be to allow full-on custom templatization by providing a view root path like you suggest.  It'd have to also make the frontend CSS/JS stuff customizable, so it'd be a bit more refactoring.

I think probably people would dig that for their own installs, but it probably won't ever be any kind of huge win for the main site.  If you wanna do something like this, I'd suggest trying it out in a fork.  Factor out the "default" styling, and then show an example of how an alternative style could be configured with a one-liner in the local.json.
