### ISSUE TITLE
Default checkbox should be checked for replies to post

### ISSUE THREAD

**Issue by ednapiranha** [bigboringsystem/bigboringsystem#140]
Located in /profile and in a new post

**Comment by ednapiranha** [comment]
for @thefoxis to review when ready

**Comment by isaacs** [comment]
I think the best way to do this is to set `user.showreplies=true` if `user.showreplies===undefined` in the lookup in posts, and set it to true on new user creation.

Posts default to the user setting, so basically, just make the user setting true by default.

**Comment by coleGillespie** [comment]
ill take it if you want to assign @ednapiranha

**Comment by isaacs** [comment]
@coleGillespie GH doesn't let you assign non-committers, but I'll be happy to review it if you make a PR.

**Comment by coleGillespie** [comment]
should be ready to review

**Comment by isaacs** [comment]
Part 1 (new user defaults to checked) done in #140.

@ednapiranha If you want to migrate all the preexisting users to check the box if it's set to undefined, that's probably better done with a migration script rather than special casing like i'd suggested above.  Or we could just leave it, and let them opt-in.

**Comment by ednapiranha** [comment]
let's leave it as opt-in for older users.
