### ISSUE TITLE
Time displaying in un processed UTC

### ISSUE THREAD

**Issue by TheAlphaNerd** [bigboringsystem/bigboringsystem#180]
Is that expected?

**Comment by isaacs** [comment]
No, I don't think so.

But I love it, personally.

Looks like the time stuff isn't in global.js any more. @ednapiranha did you change it on the server or something?  It's definitely there in dev.

Oh gosh.  I love it so much.  So clean and lovely.  Let's get rid of time zones forever.

**Comment by jasonrhodes** [comment]
I was seeing this too but it was a browser cache of global.js because we're not doing client side JS versioning of any kind. Going to http://bigboringsystem.com/js/global.js?a=b verified the same file that's in master, which *should* convert to local to...

Is that the case for you all too?

*If people want to revert that change and go full UTC, makes no difference to me :)

**Comment by isaacs** [comment]
I think the issue was that the nginx workers weren't restarted after the update, so some had the old js in THEIR caches.

@ednapiranha restarted the server, and it works for me now.
