### ISSUE TITLE
Post editing

### ISSUE THREAD

**Issue by remixz** [bigboringsystem/bigboringsystem#58]
i think post editing can be beneficial as long as it isn't a secret that a post was edited. for me, i like to know when something has changed in a piece of writing, so if i had already read it, i know to give it a look again, and that if something has changed, i'm not crazy for thinking it was a different way before. :wink:  

my thinking is that post editing would be allowed, but a reason must be given, all posts would be versioned, and all versions of a post could be accessed by anyone. this holds someone accountable for what they write, as they can't silently edit it to change the dynamic of a post. however, it allows for people to fix grammatical mistakes, or to potentially clarify a topic. 

if edited, the post would show the timestamp of when it was posted, and when it was last edited. going to a post's permalink would show the old versions, along with the edit reasons. there could potentially be an edit limit as well, since if you have to edit a post over and over, it's probably better off as a new post.

on the other hand though, part of me thinks that no editing is fine, and that if something needs clarification, one could just reply to their own post. i figured i'd post my idea here for feedback though, to see what everyone else thinks.

**Comment by isaacs** [comment]
@remixz I'm loathe to shut you down, but yeah, I think maybe it's a bit overkill, and will encourage some unpleasant habits.

At the moment, `x delete` sounds ominous, and it comes at a cost.  It doesn't seem like a thing that should be done capriciously.  It *feels* like it's going to break links.  I think that's a Good Thing.

If we make it too easy to "delete and repost" so that people can edit, then it sort of changes the feel of bbs in a way that removes some of its magic.  It isn't just "a place to write a thing", it's "a place to write a thing, and then polish it to perfection", and we already have like 80 zillion of those.  Bbs should be like twitter for blogging (without ever being like twitter for Brand Engagement), and I think a lot of twitter's magic comes from the fact that you *can't* edit tweets, and since "delete and repost" is a psychologically costly action, we instead just have to exercise some care before posting, and we'll tend to be accepting of errors in the posts of others.

This is all of course really artsy fartsy and esthetic and subjective, so if a bunch of other users come asking for this, then let's re-open.
