### ISSUE TITLE
Login attempts banning doesn't make sense?

### ISSUE THREAD

**Issue by spinda** [bigboringsystem/bigboringsystem#78]
Why does this ban the phone the user is trying to log in with? Shouldn't it ban their IP or something instead? The way it is now, if I know someone's phone number, I can ban them from BBS by making three quick login attempts.

**Comment by TheAlphaNerd** [comment]
This does seem particularly nasty

**Comment by isaacs** [comment]
Agreed!  It's also a security exploit, since you can post a zillion login attempts with different phone numbers, and cost the admin a bundle.

Fixed on https://github.com/bigboringsystem/bigboringsystem/commit/2a7fb7a0c5768aca077f014dfe3abb65e13a47b3, and @ednapiranha confirmed that it was pushed to bigboringsystem.com today.
