### ISSUE TITLE
Override Twilio creds when testing

### ISSUE THREAD

**Issue by isaacs** [bigboringsystem/bigboringsystem#90]
If `process.env.NODE_ENV === 'test'` or `process.env.npm_lifecycle_event === 'test' or 'dev'` then don't even try to load the Twilio client, and instead use a mock or some crap.

Add `scripts.dev` to package.json, which is the same as `scripts.start` except that the `npm_lifecycle_event` env will be set to `'dev'` so we can key on it, and know it's not production.

If Twilio creds aren't there, and it's not test mode, then print out a friendly message that you need to `npm run dev` or set up a twilio account, and die gracefully, instead of having the Twilio client print out obscure errors.

Once we do that, I think we're in a state where Travis will start to Just Work, and newbs who just wanna try something out and make sure tests work won't have to set up a Twilio account.

**Comment by TheAlphaNerd** [comment]
I'd be interested in helping out with this one... I'll dig into it when I get back to the city.  Is scripts.dev loaded with functionality?  I've been doing ```npm run start-dev``` for a while, having ```npm dev``` would be fantastic!

**Comment by isaacs** [comment]
Nope, `dev` is semantics-free.  You do have to do `npm run dev`, though, not just `npm dev`.

**Comment by TheAlphaNerd** [comment]
do you think that it would make sense to make ```dev``` a default like ```start```.  I see quite a bit of value in having two default run environments that have short hands.

SorryNotSorry for feature creeping.

I'll make an issue over on npm if you are interested in exploring this

**Comment by isaacs** [comment]
You can open an issue. But it isn't on the roadmap, and won't happen in
2015, or probably any of the other years. :)

**Comment by TheAlphaNerd** [comment]
I guess I'll live with the five extra characters. Aka one extra tab

**Comment by joates** [comment]
this is something i was planning to work on today but i have a terrible headache, so may not make much/any significant progress.

i think a logic switch in the local config would be my preferred implementation (i've implemented this type of solution before using [rc](https://github.com/dominictarr/rc)), it's not much additional work, doesn't impact on the existing functionality and it's not much extra code either.

i do not want to create an account with Twilio if i am just doing some UI / nav / etc hacking..
specifically because of these clauses in the ToS:

> 3.2  Net of Taxes. Unless otherwise stated in the Rate Schedule, all applicable federal, state or local taxes and all use, sales, commercial, gross receipts, privilege, surcharges, or other similar taxes, license fees and surcharges, whether charged to or against Twilio, will be payable by Customer.

_i do not reside in the US_

> 7.1  Term. The term of this Agreement will commence on the date this Agreement is accepted by Customer and continue for a **period of twelve months**.

**Comment by jasonrhodes** [comment]
I've got some of this done, I hate having to check if "in test mode" inside of the actual code but it seems to be the easiest and most reliable way to do some of this for right now, anyway. I should have PR for people to comment on later this afternoon.

**Comment by jasonrhodes** [comment]
Oops, I had this open last night and only just noticed @TheAlphaNerd's comments -- Myles are you working on this already? I've got some of it done on my branch too but if you're moving on it, go for it.

**Comment by TheAlphaNerd** [comment]
Nope, go for it!

**Comment by isaacs** [comment]
If I were to do this, I'd create a single `lib/twilio.js` or something, that checks the config/env and either creates a client, or creates a mock client.  Then the rest of the codebase can just behave normally as if it's production, instead of littering switches all over the place.

**Comment by joates** [comment]
so far all i have is a small patch that uses [nock](https://github.com/pgte/nock)
code is [here](https://github.com/joates/bigboringsystem/commit/a0d6fd7c0f9d316b27ae67daa6554d6ae4c2156a)
it's not ready to PR because there are other issues to consider..

such as:
* when you initially deploy the system there are no existing users, so you have to use something like [postman](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en) to add a single user to the blank db
* you also need to add the uid you just created into the local.json config as an "op" or the homepage won't load

FYI: i wasn't sure which properties the Twilio response contains so i just added *everything* in there :)

**Comment by isaacs** [comment]
I think Nock is a bit overkill.  We literally use the twilio client for a single thing, so it's probably easier to just stub out that function, and call the callback as if it succeeded.

**Comment by joates** [comment]
@isaacs agreed.. i won't do any more work on this

but it does get me over the obstacle of not being able to login and not being able to make posts on my forked local system, so at least i have something to work with now :)

**Comment by isaacs** [comment]
@joates At the least, you can do `NODE_ENV=test npm start` and then just get the pin dumped out to the terminal, but you have to use the phone number `15555555` as well.

Mostly this is just a code organization/cleanup task.

**Comment by joates** [comment]
thanks @isaacs thats good to know, so [var client](https://github.com/bigboringsystem/bigboringsystem/blob/master/lib/utils.js#L16) is really doing nothing, i've been asking myself "why is that there?" for most of the day (i have _a lot_ to learn :)

**Comment by isaacs** [comment]
Fixed by #95, thanks @jasonrhodes! :smile_cat:
